#define VIAL_KEYBOARD_UID \
    { 0xBF, 0x98, 0x40, 0x93, 0x5B, 0x4A, 0x41, 0x98 }

#define VIAL_UNLOCK_COMBO_ROWS \
    { 0, 3 }
#define VIAL_UNLOCK_COMBO_COLS \
    { 0, 4 }

#define DYNAMIC_KEYMAP_LAYER_COUNT 8

#define VIAL_COMBO_DISABLE

#define VIAL_COMBO_ENTRIES 16
#define VIAL_TAP_DANCE_ENTRIES 8

#define MK_COMBINED

#define MOUSEKEY_DELAY 0
#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_WHEEL_DELAY 0
#define MOUSEKEY_MAX_SPEED 6
#define MOUSEKEY_TIME_TO_MAX 64

#define TAPPING_TERM 200
#define TAP_HOLD_CAPS_DELAY 20

#define COMBO_TERM 50
